350258: Add Generate Flux Manifests scaffolder steps
DEFRA/adp-software-templates pull request #40
Opened 2024-04-05 21:30 UTC by jamescoxheadcapgemini

# **What this PR does / why we need it**:
Adds scaffolder step to generate Flux manifests. [AB#350258](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/350258)

# **Special notes for your reviewer**
This should not be merged in until team configurations have been created for all project teams onboarded in to the portal, otherwise the scaffolder will not be able to complete this action!

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [x] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [x] Title pattern should be `{work item number}: {title}`
- [x] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-04-08 08:10 UTC, DaRoszko commented on templates/adp-backend-template-node/template.yaml
> +      name: Generate Flux Manifests
Might be best to be called, in the UI to the user, "Generate Service (Flux) Manifests"

Basically to them it's there Service Manifest or Service Configuration.. it just so happens we use Flux as a tool to do it.

2024-04-17 12:55 UTC, danny-may commented
I think we need these changes made to the empty template too

2024-04-18 13:11 UTC, danny-may approved these changes

2024-04-18 13:17 UTC, kbabigumira approved these changes

2024-04-18 13:18 UTC, DaRoszko approved these changes

2024-04-18 13:23 UTC, DaRoszko requested changes

2024-04-18 13:23 UTC, DaRoszko commented on templates/adp-empty-project-template/template.yaml
> +        method: POST
remove this from empty.. just spoke with Ken

2024-04-18 13:28 UTC, danny-may approved these changes

2024-04-18 13:29 UTC, DaRoszko approved these changes

2024-04-18 13:29 UTC, merged