341889: Helm only repo
DEFRA/adp-software-templates pull request #47
Opened 2024-04-18 15:30 UTC by jamescoxheadcapgemini

# **What this PR does / why we need it**:
Adds the Helm Only template to the scaffolder. [AB#341889](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/341889)

# **Special notes for your reviewer**
Flux manifest actions to be added when the API supports helm only projects.

# Testing
[Scaffolded template](https://github.com/defra-adp-sandpit/jc-helm-7/tree/main)
[Pipeline run](https://dev.azure.com/defragovuk/DEFRA-ADP/_build/results?buildId=532681&view=results) - I assume this is failing because the Pipelines GH app does not yet have access to the repo?

# Checklist (please delete before completing or setting auto-complete)
- [x] Story Work items associated (not Tasks)
- [x] Successful testing run(s) link provided
- [x] Title pattern should be `{work item number}: {title}`
- [x] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [x] This PR contains tests

# **How does this PR make you feel**:
![[gif]([https://giphy.com/)](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTl2NHlsZnVpMzhteHhhdTcxNTlpNnBoOGJvZGVnZzVmbzlvZTU2bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pjhIOmGXyr7pBwzpjE/giphy.gif)

2024-04-18 15:38 UTC, danny-may requested changes

2024-04-18 15:38 UTC, danny-may commented on templates/adp-helm-only-template/skeleton/pull_request_template.md
> +test
Test text?

2024-04-19 11:41 UTC, kbabigumira approved these changes

2024-04-19 12:29 UTC, DaRoszko approved these changes

2024-04-22 08:30 UTC, danny-may approved these changes

2024-04-22 08:31 UTC, merged